version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values:
                [
                  "delivered",
                  "shipped",
                  "canceled",
                  "invoiced",
                  "processing",
                  "approved",
                  "unavailable",
                  "created",
                ]

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
